config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :lists do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list # allows u to do bookmark.list
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
    # we need the :list_id because of the path /lists/:list_id/bookmarks/new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to lists_path
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end


end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      flash[:notice] = 'list added!'
      redirect_to list_path(@list)
    else
      flash[:error] = 'Failed to add list!'
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @product.save
      flash[:notice] = 'Movie added!'
      redirect_to movie_path(@movie)
    else
      flash[:error] = 'Failed to add movie!'
      render :new
    end
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :overview, :post_url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<h1>Add a new list</h1>
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.button :submit, class: "btn btn-primary"%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <div>
  <%= link_to "All lists", lists_path %>
  <%= link_to "Add lists", new_list_path %>
  </div>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>All lists</h1>

<% @lists.each do |list| %>
  <p><%= link_to list.name, list_path(list) %></p>
  <hr>
<% end %>

app/views/lists/new.html.erb
<h1>Add a new list</h1>
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit, class: "btn btn-primary"%>
<% end %>

app/views/lists/show.html.erb
<%= cl_image_tag @list.photo.key, height: 300, width: 400, crop: :fill %>
<h1><%= @list.name %></h1>
<%= link_to "Add a new bookmark", new_list_bookmark_path(@list) %>
<div>
<% @list.bookmarks.each do |bookmark| %>
<%# list can access only bookmarks because a list has_many :bookmarks (see model) And then we can access bookmarks through an iteration %>
 <p><%= bookmark.comment %></p>
 <p><%= bookmark.movie.title %></p>
 <p><%= image_tag(bookmark.movie.poster_url, size: "200x350", alt: bookmark.movie.title) %></p>
 <p><%= bookmark.movie.overview %></p>
 <p><%= bookmark.movie.rating %></p>
<% end %>
</div>

app/views/movies/index.html.erb
<h1>All movies</h1>

<% @movies.each do |movie| %>
  <p><%= movie.title %></p>
  <p><%= link_to movie.title, movie_path(movie) %></p>
  <p><%= image_tag(movie.poster_url, size: "200x300", alt: movie.title) %></p>
  <p><%= movie.overview %></p>
  <p><%= movie.rating %></p>
  <hr>
<% end %>

app/views/movies/new.html.erb
<h1>Add a new movie</h1>
<%= simple_form_for @movie do |f| %>
  <%= f.input :title %>
  <%= f.input :overview %>
  <%= f.input :poster_url, placeholder: 'www.movie-image.com' %>
  <%= f.button :submit, class: "btn btn-primary"%>
<% end %>